
CREATE DATABASE reprotek;
USE reprotek;

CREATE TABLE Role
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	role VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE StateMaster
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TypeApparatus
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE
);

GO

CREATE TABLE Users
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nameFirst VARCHAR(30) NOT NULL,
	nameLast VARCHAR(30) NOT NULL,
	nameMiddle VARCHAR(30) NOT NULL,
	telephone VARCHAR(12) NOT NULL UNIQUE,
	email VARCHAR(12) NOT NULL UNIQUE,
);

CREATE TABLE Company
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE StateApparatus
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE
);

