
DROP DATABASE reprotek;

CREATE DATABASE reprotek;
USE reprotek;

CREATE TABLE role(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE user(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_role INT DEFAULT NULL,

	nameFirst VARCHAR(100) NOT NULL,
	nameLast VARCHAR(100) NOT NULL,
	nameMiddle VARCHAR(100),

	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,

	FOREIGN KEY (id_role) REFERENCES role (id) ON DELETE SET NULL
);
